In [9]:
import sklearn.metrics
import numpy as np
import pandas as pd

In [26]:
a = (np.random.random(10) > 0.5) * 1.0
b =  np.random.random(10)

In [27]:
print a
print b

[ 1.  1.  1.  0.  0.  1.  0.  1.  1.  0.]
[ 0.28161233  0.73893792  0.98442404  0.61169145  0.05905818  0.36161902
  0.44427996  0.22238411  0.72670835  0.01114842]


In [50]:
b[1],b[3] = b[3],b[1]

In [51]:
b

array([ 0.28161233,  0.61169145,  0.98442404,  0.73893792,  0.05905818,
        0.36161902,  0.44427996,  0.22238411,  0.72670835,  0.01114842])

In [49]:
np.argmax(a == 0.0)

3

In [30]:
print a.dtype
print b.dtype

float64
float64


In [32]:
sklearn.metrics.mean_squared_error(a,b)

0.22465451991341867

In [33]:
sklearn.metrics.accuracy_score(a,b > 0.5)

0.59999999999999998

In [34]:
sklearn.metrics.log_loss(a,b)

0.60307376800891599

In [43]:
sklearn.metrics.precision_recall_fscore_support(a,b > 0.5)

(array([ 0.5 ,  0.75]),
 array([ 0.75,  0.5 ]),
 array([ 0.6,  0.6]),
 array([4, 6]))