In [9]:
import sklearn.metrics
import numpy as np
import pandas as pd

In [26]:
a = (np.random.random(10) > 0.5) * 1.0
b =  np.random.random(10)

In [27]:
print a
print b

[ 1.  1.  1.  0.  0.  1.  0.  1.  1.  0.]
[ 0.28161233  0.73893792  0.98442404  0.61169145  0.05905818  0.36161902
  0.44427996  0.22238411  0.72670835  0.01114842]


In [50]:
b[1],b[3] = b[3],b[1]

In [51]:
b

array([ 0.28161233,  0.61169145,  0.98442404,  0.73893792,  0.05905818,
        0.36161902,  0.44427996,  0.22238411,  0.72670835,  0.01114842])

In [49]:
np.argmax(a == 0.0)

3

In [30]:
print a.dtype
print b.dtype

float64
float64


In [32]:
sklearn.metrics.mean_squared_error(a,b)

0.22465451991341867

In [33]:
sklearn.metrics.accuracy_score(a,b > 0.5)

0.59999999999999998

In [34]:
sklearn.metrics.log_loss(a,b)

0.60307376800891599

In [43]:
sklearn.metrics.precision_recall_fscore_support(a,b > 0.5)

(array([ 0.5 ,  0.75]),
 array([ 0.75,  0.5 ]),
 array([ 0.6,  0.6]),
 array([4, 6]))

In [3]:
curves = {
        "samples": 345,
        "chan": 5,
        "tag": "abc",
        "model": {
            "patch_size": 423543,
            "ident": "xyz",
        },
        "train": {
            "loss":    0.45,
            "mse":     0.45,
            "acc":     0.25,
            "prec":    0.85,
            "recall":  0.218,
            "fscore":  0.23987,
            "support": 0.348
            },
        "valid": {
            "loss": 0.458,
            "mse": 0.4598,
            "acc": 0.35,
            "prec": 0.234,
            "recall": 0.545,
            "fscore": 0.54837,
            "support": 0.346
        }     
    }

In [5]:
def flatten(d):
    def items():
        for key, value in d.items():
            if isinstance(value, dict):
                for subkey, subvalue in flatten_dict(value).items():
                    yield key + "." + subkey, subvalue
            else:
                yield key, value

    return dict(items())

In [7]:
curves = flatten(curves)

In [12]:
df = pd.DataFrame(columns=curves.keys())

In [13]:
df = df.append(curves, ignore_index=True)

In [14]:
df

train.fscore  valid.fscore  valid.loss  train.prec  valid.support  \
0       0.23987       0.54837       0.458        0.85          0.346   

   valid.recall  chan  model.patch_size  train.acc  train.recall model.ident  \
0         0.545   5.0          423543.0       0.25         0.218         xyz   

   valid.mse  valid.prec  tag  train.support  valid.acc  samples  train.mse  \
0     0.4598       0.234  abc          0.348       0.35    345.0       0.45   

   train.loss  
0        0.45